import type {ITransportClient, TaskAck} from '@campfirein/brv-transport-client'

import {randomUUID} from 'node:crypto'
import {existsSync} from 'node:fs'
import {lstat, mkdir, readFile, rm, unlink, writeFile} from 'node:fs/promises'
import {dirname, join} from 'node:path'
import {z} from 'zod'

import type {CurateHtmlDirectResult} from '../../server/core/interfaces/executor/i-curate-executor.js'
import type {HtmlWriteError} from '../../server/infra/render/writer/html-writer.js'
import type {CurateMeta} from '../../shared/curate-meta.js'

import {BRV_DIR} from '../../server/constants.js'
import {buildCorrectionPrompt, buildGeneratePrompt} from '../../server/core/domain/render/curate-prompt-builder.js'
import {CurateMetaSchema} from '../../shared/curate-meta.js'
import {encodeCurateHtmlContent} from '../../shared/transport/curate-html-content.js'
import {TaskEvents} from '../../shared/transport/events/index.js'
import {waitForTaskCompletion} from './task-client.js'

/**
 * Curate session protocol — CLI-side orchestrator for the multi-step
 * curate flow that byterover-tool-mode introduces.
 *
 * Background. `brv curate` runs no LLM inside byterover. The calling
 * agent (Claude Code) owns the LLM, byterover validates + writes.
 * Because a subprocess can't call back into its parent, the protocol
 * is multi-step: kickoff returns `needs-llm-step` with a prompt; the
 * calling agent produces the response and re-invokes `brv curate` with
 * `--session`/`--response`. Byterover holds session state between
 * invocations.
 *
 * Dispatch. Continuation routes the validated `<bv-topic>` HTML through
 * the daemon's `curate-tool-mode` task type — the same type the MCP
 * `brv-curate` tool already uses. This converges CLI and MCP on one
 * write path, so every CLI curate produces a `TaskHistoryEntry` and
 * surfaces in the WebUI Tasks panel, `brv task list`, and cancel
 * surfaces (TaskRouter's TaskHistoryHook fires automatically).
 *
 * Session state. Kickoff and the retry-cap loop stay file-based on the
 * CLI side (`<projectRoot>/.brv/sessions/curate-<id>/state.json`) — only
 * the write itself runs server-side. M3 cleanup may move session state
 * into daemon task-session sandbox vars later.
 *
 * State machine. The orchestrator drives:
 *
 *   kickoff(text)
 *     → state = pending-generate, attempts = 0
 *     → emit needs-llm-step, step = generate-html
 *
 *   continue(response) on pending-generate
 *     → dispatch curate-tool-mode (daemon validates + writes)
 *       on success → emit done, clear session
 *       on failure → state = pending-correct, emit needs-llm-step / correct-html
 *
 *   continue(response) on pending-correct
 *     → dispatch curate-tool-mode
 *       on success → emit done, clear session
 *       on failure → attempts++; if attempts >= MAX_ATTEMPTS → emit failed,
 *                    else stay in pending-correct, emit correct-html
 *
 * `MAX_ATTEMPTS = 4` (one initial generate + three corrections). After
 * the fourth invalid response the orchestrator terminates the session
 * with `status: failed`.
 *
 * Deliberately deferred:
 *   - Search-first UPDATE detection — kickoff emits a generic
 *     generate-html prompt; UPDATE vs CREATE is the calling agent's
 *     responsibility for now.
 *   - 1h session TTL — abandoned sessions accumulate on disk; M3 prunes
 *     when state moves into the daemon's task-session lifecycle.
 */

export const CURATE_SESSIONS_DIR = 'sessions'
export const CURATE_SESSION_PREFIX = 'curate-'

/** Maximum number of LLM responses we'll validate before terminating with `failed`. */
const MAX_ATTEMPTS = 4

/**
 * Session ids are uuids generated by `randomUUID()` in `kickoffSession`.
 * Validating that any incoming `--session` argument matches this shape
 * before joining it into a filesystem path closes a path-traversal hole:
 * without this check, a hostile `--session "../../etc"` would let
 * `clearSessionState` rm a directory outside `.brv/sessions/`.
 */
const SESSION_ID_RE = /^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/i

/**
 * Wire envelope returned by both kickoff and continuation calls.
 * Stable. Reviewer note in the task file: renaming a key here is a
 * breaking change once SKILL.md (TKT 04) ships against this shape.
 */
/** Flat error shape carried in the envelope's `errors` array. */
export type CurateSessionError = {
  attribute?: string
  /**
   * Present on `kind: 'path-exists'` when the prior file was readable.
   * Carries the existing file's full bytes so the calling agent can
   * merge new content into the existing topic instead of silently
   * clobbering it. Mirrors what is embedded inline into the correction
   * prompt. Absent (`undefined`) when the file exists but its content
   * could not be read — consumers MUST treat that as "prior content
   * unavailable", NOT as "topic is empty".
   */
  existingContent?: string
  kind: string
  message: string
  tag?: string
}

export type CurateSessionEnvelope = {
  /** Validation errors. Present on `correct-html` steps and on terminal `failed`. */
  errors?: CurateSessionError[]
  /**
   * Path to the written topic file. Relative to `<projectRoot>/.brv/context-tree/`
   * (e.g. `security/auth.html`). Present when `status === 'done'`.
   */
  filePath?: string
  /** Aggregated success flag — `true` when the overall protocol made progress (not the LLM-step result). */
  ok: boolean
  /** Free-text instruction for the calling agent's LLM. TKT 03 replaces the stubs with the real prompts. */
  prompt?: string
  /** Optional per-step schema slice (e.g. bv-* spec subset). TKT 03 populates. */
  schema?: object
  /**
   * Session identifier for subsequent continuations. Present on every
   * `needs-llm-step` envelope AND on transient `failed` envelopes
   * (e.g. `kind: empty-response`) where the session remains live and
   * the caller is expected to retry. Absent on terminal failures
   * (`kind: unknown-session`, `missing-content`, `missing-response`,
   * `retry-cap-exceeded`) and on `done`.
   */
  sessionId?: string
  status: 'done' | 'failed' | 'needs-llm-step'
  /** Tells the calling agent what kind of completion to produce. */
  step?: 'correct-html' | 'generate-html'
  /**
   * Advisory warnings from the writer (today: broken `related` refs
   * surfaced by the read-only resolver). Present on `done` envelopes
   * whenever the write succeeded but the writer surfaced post-write
   * warnings; omitted when the warning list is empty so consumers do
   * not see a noisy `"warnings": []` on every clean curate.
   */
  warnings?: readonly string[]
}

/**
 * On-disk session record. The state machine reads and writes this on
 * every continuation. Type-guarded on read so a corrupted file is
 * treated as "no session" instead of propagating malformed fields.
 */
type CurateSessionState = {
  /**
   * Count of LLM responses we've validated so far against this session.
   * Increments on every continuation. When this reaches `MAX_ATTEMPTS`
   * after another invalid response, the orchestrator terminates with
   * `status: failed` and clears the session.
   */
  attempts: number
  createdAt: number
  /**
   * Most recent invalid HTML response. Carried so the next
   * correct-html prompt can show the calling agent what it just
   * produced (correction works better with concrete previous context
   * than starting from scratch). Empty when the session has only
   * emitted a generate-html step so far.
   */
  lastResponse: string
  /** Which step the orchestrator most recently emitted. */
  step: 'awaiting-correct' | 'awaiting-generate'
  /** The user's original `brv curate "<text>"` argument. */
  userIntent: string
}

type KickoffOptions = {
  content: string
  projectRoot: string
}

type ContinueOptions = {
  /** Connected daemon transport client — used to dispatch the curate-tool-mode task. */
  client: ITransportClient
  /**
   * Opt-in to clobber an existing topic at the resolved path. Default
   * `false`: the writer's overwrite guard surfaces `path-exists` as a
   * correctable validation error. Set `true` only when the calling
   * agent has consciously decided to replace prior content (today
   * surfaced via the `--overwrite` flag on `brv curate --session …`).
   */
  confirmOverwrite?: boolean
  /**
   * CLI output format. Threaded into the daemon dispatch's
   * `waitForTaskCompletion` so the stale-check fallback uses the same
   * channel as the CLI (no JSON envelope leaking onto stdout in text
   * mode). Defaults to 'json' — matches the agent-facing default.
   */
  format?: 'json' | 'text'
  projectRoot: string
  response: string
  sessionId: string
}

/**
 * Kickoff a new session. Persists state and returns the
 * `needs-llm-step` / generate-html envelope. No validation runs here —
 * kickoff is just "register the user intent and ask the calling agent
 * to author HTML".
 */
export async function kickoffSession(options: KickoffOptions): Promise<CurateSessionEnvelope> {
  const {content, projectRoot} = options
  const sessionId = randomUUID()

  const state: CurateSessionState = {
    attempts: 0,
    createdAt: Date.now(),
    lastResponse: '',
    step: 'awaiting-generate',
    userIntent: content,
  }

  await writeSessionState(projectRoot, sessionId, state)

  return {
    ok: true,
    prompt: buildGeneratePrompt({userIntent: content}),
    sessionId,
    status: 'needs-llm-step',
    step: 'generate-html',
  }
}

/**
 * Parsed CLI envelope response. Mirrors the MCP tool's typed input but
 * arrives as a JSON string on the `--response` flag, so we have to
 * parse + validate here. `meta` is optional — agents that don't supply
 * it still curate successfully (just no review surfacing for that entry).
 */
const CurateResponseEnvelopeSchema = z.object({
  html: z.string().min(1),
  meta: CurateMetaSchema.optional(),
})

/**
 * Custom error thrown by `parseCurateResponse` when the agent's response
 * is not a well-formed envelope. Carries `kind: 'invalid-response-format'`
 * so the orchestrator can map it to the envelope's structured `errors[]`
 * shape without coupling parsing to envelope construction.
 *
 * Exported so the CLI command layer can narrow with `instanceof` instead
 * of duck-typing on `error.kind`.
 */
export class InvalidResponseFormatError extends Error {
  readonly kind = 'invalid-response-format'
}

/**
 * Discriminated `kind` for `InvalidResponseFileError`. Each branch maps
 * 1:1 to a CLI envelope error kind so the calling agent can switch on
 * `kind` without learning the helper's internals:
 *
 *   - `response-file-not-regular` — path resolves to a symlink, directory,
 *     socket, fifo, etc. The CLI refuses to read or unlink anything that
 *     isn't a plain file to avoid surprise filesystem mutation.
 *   - `response-file-read-error` — `lstat` or `readFile` failed (ENOENT,
 *     permissions, low-level I/O error).
 *   - `response-file-delete-error` — `unlink` failed after a regular-file
 *     guard succeeded. Could be EACCES, the file vanished between lstat
 *     and unlink, or a filesystem error.
 */
export type ResponseFileErrorKind =
  | 'response-file-delete-error'
  | 'response-file-not-regular'
  | 'response-file-read-error'

/**
 * Thrown by `loadCurateResponseFile` and `deleteCurateResponseFile` when
 * the file path supplied via `--response-file` (or its deletion request)
 * cannot be honored. Carries a structured `kind` so the CLI command can
 * map the failure into a typed envelope error.
 */
export class InvalidResponseFileError extends Error {
  readonly kind: ResponseFileErrorKind

  constructor(kind: ResponseFileErrorKind, message: string) {
    super(message)
    this.kind = kind
  }
}

/**
 * Read the JSON envelope from `filePath` and return its raw contents.
 *
 * Guards against non-regular files (symlinks, directories, devices) via
 * `lstat` before touching `readFile`. Returning a non-regular path's
 * bytes would let a hostile symlink redirect the read to an unintended
 * location, and a directory would surface as a misleading EISDIR. We
 * reject up front with a stable structured error.
 *
 * Throws `InvalidResponseFileError` with one of:
 *   - `kind: 'response-file-not-regular'` — path resolved to a non-file.
 *   - `kind: 'response-file-read-error'` — lstat or readFile failed.
 */
export async function loadCurateResponseFile(filePath: string): Promise<string> {
  const stats = await safeLstat(filePath, 'response-file-read-error', 'read')
  if (!stats.isFile()) {
    throw new InvalidResponseFileError(
      'response-file-not-regular',
      `--response-file expects a regular file; \`${filePath}\` is a ${describeFileKind(stats)}.`,
    )
  }

  try {
    return await readFile(filePath, 'utf8')
  } catch (error) {
    throw new InvalidResponseFileError(
      'response-file-read-error',
      `Cannot read --response-file at \`${filePath}\`: ${formatFsError(error)}.`,
    )
  }
}

/**
 * Delete the JSON envelope file at `filePath` after it has been
 * successfully consumed (read + parsed + envelope-validated upstream).
 *
 * Same regular-file guard as `loadCurateResponseFile` — never unlinks a
 * symlink, directory, or device. Caller is expected to gate this on
 * local validation success (the envelope was read, JSON-parsed, and
 * schema-validated) before invoking — the file is only safe to remove
 * once we've extracted everything we need from it.
 *
 * Throws `InvalidResponseFileError` with
 * `kind: 'response-file-delete-error'` on any failure (non-regular path,
 * lstat failure, unlink failure). The CLI command surfaces this as a
 * structured envelope error and skips the daemon dispatch — we never
 * pretend a curate succeeded when the requested cleanup did not.
 */
export async function deleteCurateResponseFile(filePath: string): Promise<void> {
  const stats = await safeLstat(filePath, 'response-file-delete-error', 'delete')
  if (!stats.isFile()) {
    throw new InvalidResponseFileError(
      'response-file-delete-error',
      `Refusing to delete \`${filePath}\` — not a regular file (${describeFileKind(stats)}).`,
    )
  }

  try {
    await unlink(filePath)
  } catch (error) {
    throw new InvalidResponseFileError(
      'response-file-delete-error',
      `Failed to delete --response-file at \`${filePath}\`: ${formatFsError(error)}.`,
    )
  }
}

function describeFileKind(stats: Awaited<ReturnType<typeof lstat>>): string {
  if (stats.isDirectory()) return 'directory'
  if (stats.isSymbolicLink()) return 'symbolic link'
  if (stats.isBlockDevice() || stats.isCharacterDevice()) return 'device'
  if (stats.isFIFO()) return 'fifo'
  if (stats.isSocket()) return 'socket'
  return 'non-regular file'
}

// Node's `fs/promises` errors carry the errno code (e.g. "ENOENT") at the
// start of `message` already, so we surface `message` verbatim — no extra
// `${code}:` prefix to avoid the "ENOENT: ENOENT: …" double-tag.
function formatFsError(error: unknown): string {
  if (error instanceof Error) return error.message
  return String(error)
}

async function safeLstat(
  filePath: string,
  errorKind: ResponseFileErrorKind,
  verb: 'delete' | 'read',
): Promise<Awaited<ReturnType<typeof lstat>>> {
  try {
    return await lstat(filePath)
  } catch (error) {
    throw new InvalidResponseFileError(
      errorKind,
      `Cannot ${verb} --response-file at \`${filePath}\`: ${formatFsError(error)}.`,
    )
  }
}

/**
 * Parse the agent's `--response` payload as a JSON envelope `{html, meta?}`.
 *
 * The CLI session protocol used to accept raw HTML on `--response`; M4
 * switches to a structured envelope so the calling agent's LLM can
 * supply operation metadata (impact, type, reason) alongside the HTML
 * for the HITL review pipeline.
 *
 * Throws `InvalidResponseFormatError` with `kind: 'invalid-response-format'`
 * on malformed JSON, missing/empty `html`, or invalid `meta`. The caller
 * (continueSession) catches and maps to a structured envelope error so
 * the calling agent sees a clear "your response shape was wrong" signal
 * pointing at the envelope contract.
 */
export function parseCurateResponse(raw: string): {html: string; meta?: CurateMeta} {
  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch {
    throw new InvalidResponseFormatError(
      '--response must be a JSON envelope `{"html": "<bv-topic>...</bv-topic>", "meta": {...}}`. Got non-JSON input.',
    )
  }

  const result = CurateResponseEnvelopeSchema.safeParse(parsed)
  if (!result.success) {
    const issue = result.error.issues[0]
    const field = issue?.path.join('.') || '<root>'
    throw new InvalidResponseFormatError(
      `--response envelope failed validation at \`${field}\`: ${issue?.message ?? 'unknown error'}. Expected \`{"html": "<bv-topic>...</bv-topic>", "meta": {...}}\`.`,
    )
  }

  return {html: result.data.html, meta: result.data.meta}
}

/**
 * Lookup an existing session without dispatching anything. Lets the CLI
 * command layer prove the session is live before doing destructive side
 * effects (e.g. unlinking a `--response-file`). Same UUID guard as
 * `continueSession` to keep the path-traversal threat model intact.
 *
 * Returns a discriminator only — the actual `CurateSessionState` is
 * internal. Callers that need state walk it via `continueSession` (which
 * re-reads the same path; idempotent for safety).
 */
export async function peekCurateSession(
  projectRoot: string,
  sessionId: string,
): Promise<{kind: 'invalid-format'} | {kind: 'not-found'} | {kind: 'ok'}> {
  if (!SESSION_ID_RE.test(sessionId)) return {kind: 'invalid-format'}
  const state = await readSessionState(projectRoot, sessionId)
  return state ? {kind: 'ok'} : {kind: 'not-found'}
}

/**
 * Continue an existing session. Validates the response envelope,
 * dispatches the `<bv-topic>` HTML through the daemon's
 * `curate-tool-mode` task type for validation + write, advances the
 * retry loop on validation failure, terminates with `failed` once the
 * retry cap is exhausted.
 *
 * All write-side concerns (HTML validation, file write, log entry,
 * review backup, sidecar bump, index regeneration) live in the daemon's
 * `curate-tool-mode` handler — see `agent-process.ts`. This function
 * is the session-protocol envelope only.
 */
export async function continueSession(options: ContinueOptions): Promise<CurateSessionEnvelope> {
  const {client, confirmOverwrite = false, format = 'json', projectRoot, response, sessionId} = options

  // Reject non-uuid session ids before any path join — see SESSION_ID_RE
  // for the threat model. Same `kind` as "session not found" because
  // both end at the same caller-facing outcome (resume failed) and
  // distinguishing the two would leak that we're path-traversal-checking.
  if (!SESSION_ID_RE.test(sessionId)) {
    return unknownSessionEnvelope(sessionId, 'invalid-format')
  }

  const state = await readSessionState(projectRoot, sessionId)
  if (!state) return unknownSessionEnvelope(sessionId, 'not-found')

  // Empty-response is a transient continuation error: the session
  // remains live so the caller can retry without losing context.
  if (response.trim().length === 0) {
    return {
      errors: [{kind: 'empty-response', message: 'Continuation --response must be non-empty.'}],
      ok: false,
      sessionId,
      status: 'failed',
    }
  }

  // Parse the JSON envelope before dispatching to the daemon. A malformed
  // envelope is a protocol-level failure (agent didn't follow the
  // contract) — distinct from HTML validation failure (agent followed
  // the contract but the HTML inside is wrong). The session stays
  // alive so the caller can retry with a corrected envelope.
  let parsed: {html: string; meta?: CurateMeta}
  try {
    parsed = parseCurateResponse(response)
  } catch (error) {
    if (error instanceof InvalidResponseFormatError) {
      return {
        errors: [{kind: error.kind, message: error.message}],
        ok: false,
        sessionId,
        status: 'failed',
      }
    }

    throw error
  }

  const {html, meta} = parsed

  // Dispatch the validation + write through the daemon. TaskRouter's
  // TaskHistoryHook persists the lifecycle automatically, so this curate
  // appears in the WebUI Tasks panel and is cancellable from any surface.
  // userIntent rides along so the row title shows the user's original
  // prompt instead of the raw HTML blob.
  const writeResult = await dispatchCurateHtmlDirect({
    client,
    confirmOverwrite,
    format,
    html,
    meta,
    projectPath: projectRoot,
    userIntent: state.userIntent,
  })

  // Advance retry counter on every continuation — matches pre-dispatch
  // behavior so the cap fires after the same number of invalid responses.
  state.attempts += 1
  state.lastResponse = response

  if (writeResult.status === 'ok') {
    await clearSessionState(projectRoot, sessionId)
    return {
      filePath: writeResult.filePath,
      ok: true,
      status: 'done',
      ...(writeResult.warnings && writeResult.warnings.length > 0 ? {warnings: writeResult.warnings} : {}),
    }
  }

  // Validation failed. Retry cap reached → terminate the session.
  if (state.attempts >= MAX_ATTEMPTS) {
    await clearSessionState(projectRoot, sessionId)
    return {
      errors: [
        {
          kind: 'retry-cap-exceeded',
          message: `Curate session exceeded ${MAX_ATTEMPTS - 1} corrections without producing valid HTML.`,
        },
        ...writeResult.errors.map((e) => mapWriterError(e)),
      ],
      ok: false,
      status: 'failed',
    }
  }

  // Otherwise, keep the session live and ask for a correction.
  state.step = 'awaiting-correct'
  await writeSessionState(projectRoot, sessionId, state)

  return {
    errors: writeResult.errors.map((e) => mapWriterError(e)),
    ok: false,
    prompt: buildCorrectionPrompt({
      errors: writeResult.errors,
      previousHtml: response,
      userIntent: state.userIntent,
    }),
    sessionId,
    status: 'needs-llm-step',
    step: 'correct-html',
  }
}

/**
 * Dispatch a `curate-tool-mode` task to the daemon and await its
 * structured result. Same shape MCP's `brv-curate` tool uses — the
 * daemon handler owns HTML validation, write, log persistence, review
 * backup, sidecar bump, and index regeneration. Throws on transport
 * errors (the CLI command surfaces those via `withDaemonRetry`).
 */
async function dispatchCurateHtmlDirect(args: {
  client: ITransportClient
  confirmOverwrite: boolean
  format: 'json' | 'text'
  html: string
  meta?: CurateMeta
  /**
   * Threaded explicitly onto the wire payload so the daemon doesn't have
   * to fall back to client-association lookup. Mirrors MCP's brv-curate
   * dispatch and removes the worktree-edge-case ambient dependency where
   * the CLI's `resolveProjectRoot()` and the daemon's `resolveProject()`
   * (workspace-link-aware) can disagree.
   */
  projectPath: string
  userIntent: string
}): Promise<CurateHtmlDirectResult> {
  const {client, confirmOverwrite, format, html, meta, projectPath, userIntent} = args
  const taskId = randomUUID()
  const taskPayload = {
    clientCwd: process.cwd(),
    content: encodeCurateHtmlContent({confirmOverwrite, html, meta, userIntent}),
    projectPath,
    taskId,
    type: 'curate-tool-mode' as const,
  }

  let parsed: CurateHtmlDirectResult | undefined
  let errorMessage: string | undefined

  const completion = waitForTaskCompletion(
    {
      client,
      command: 'curate',
      format,
      onCompleted({result}) {
        if (!result) {
          errorMessage = 'Daemon returned an empty curate result.'
          return
        }

        try {
          parsed = JSON.parse(result) as CurateHtmlDirectResult
        } catch {
          errorMessage = 'Daemon returned a malformed curate result.'
        }
      },
      onError({error}) {
        errorMessage = error.message
      },
      taskId,
    },
    () => {
      // No-op log sink — curate emits one envelope, not progress lines.
    },
  )

  await client.requestWithAck<TaskAck>(TaskEvents.CREATE, taskPayload)
  await completion

  if (errorMessage) throw new Error(errorMessage)
  if (!parsed) throw new Error('Daemon curate-tool-mode returned no payload.')
  return parsed
}

/**
 * Build the `unknown-session` failed envelope. Used both by
 * `continueSession`'s own UUID / state-on-disk guards AND by the CLI
 * command layer when it pre-flights the session before any destructive
 * side effect (e.g. unlinking a `--response-file`). Exported so callers
 * outside this module can emit a byte-identical envelope.
 */
export function unknownSessionEnvelope(
  sessionId: string,
  reason: 'invalid-format' | 'not-found',
): CurateSessionEnvelope {
  const message =
    reason === 'invalid-format'
      ? `Invalid session id format: ${sessionId}. Expected a uuid returned by a prior kickoff.`
      : `No active session with id ${sessionId}. Either the kickoff was never run, or the session was already completed/cleaned up.`

  return {
    errors: [{kind: 'unknown-session', message}],
    ok: false,
    status: 'failed',
  }
}

/**
 * Convert an `html-writer` error to the protocol's envelope error
 * shape. The writer's shape is richer (per-element `field`/`tag`
 * disambiguation); the envelope intentionally flattens to
 * `{kind, tag?, attribute?, message}` so the calling agent can switch
 * on `kind` without learning the writer's internal taxonomy.
 */
function mapWriterError(err: HtmlWriteError): CurateSessionError {
  switch (err.kind) {
    case 'attribute-validation': {
      return {attribute: err.field, kind: 'attribute-validation', message: err.message, tag: err.tag}
    }

    case 'path-exists': {
      // Surface the prior content in a structured field so JSON-driven
      // consumers can merge without re-parsing the prompt; the same
      // content is also inlined into the correction prompt for LLM-
      // driven callers.
      return {existingContent: err.existingContent, kind: 'path-exists', message: err.message}
    }

    case 'unknown-bv-element': {
      return {kind: 'unknown-element', message: err.message, tag: err.tag}
    }

    default: {
      // missing-bv-topic, missing-path-attribute, multiple-bv-topic, unsafe-path
      return {kind: err.kind, message: err.message}
    }
  }
}

async function writeSessionState(projectRoot: string, sessionId: string, state: CurateSessionState): Promise<void> {
  const dir = sessionDir(projectRoot, sessionId)
  await mkdir(dir, {recursive: true})
  await writeFile(join(dir, 'state.json'), JSON.stringify(state, null, 2), 'utf8')
}

async function readSessionState(projectRoot: string, sessionId: string): Promise<CurateSessionState | undefined> {
  const file = join(sessionDir(projectRoot, sessionId), 'state.json')
  try {
    const raw = await readFile(file, 'utf8')
    const parsed: unknown = JSON.parse(raw)
    return isCurateSessionState(parsed) ? parsed : undefined
  } catch {
    return undefined
  }
}

/**
 * Type guard for on-disk session state. Catches corrupted writes,
 * manual edits, and schema skew — a mismatched state.json is treated
 * as "no session" rather than proceeding with garbage fields.
 */
function isCurateSessionState(value: unknown): value is CurateSessionState {
  if (typeof value !== 'object' || value === null) return false
  const record = value as Record<string, unknown>
  return (
    typeof record.attempts === 'number'
    && typeof record.createdAt === 'number'
    && typeof record.lastResponse === 'string'
    && (record.step === 'awaiting-generate' || record.step === 'awaiting-correct')
    && typeof record.userIntent === 'string'
  )
}

async function clearSessionState(projectRoot: string, sessionId: string): Promise<void> {
  await rm(sessionDir(projectRoot, sessionId), {force: true, recursive: true})
}

function sessionDir(projectRoot: string, sessionId: string): string {
  return join(projectRoot, BRV_DIR, CURATE_SESSIONS_DIR, `${CURATE_SESSION_PREFIX}${sessionId}`)
}

/**
 * Walk up from `start` (default cwd) to the nearest ancestor that
 * contains a `.brv/` marker. Falls back to `start` when no marker is
 * found upward — kickoff from a fresh project (no `.brv/` yet) will
 * create one alongside the cwd, same as today's curate behavior.
 *
 * Returning the canonical project root means a kickoff from the
 * project root and a continuation from a subdirectory land in the
 * same `.brv/sessions/` tree — without this, the second call would
 * silently fail with `unknown-session`.
 */
export function resolveProjectRoot(start: string = process.cwd()): string {
  let current = start
  while (true) {
    if (existsSync(join(current, BRV_DIR))) return current
    const parent = dirname(current)
    if (parent === current) return start // hit fs root, fall back to cwd
    current = parent
  }
}
