/* eslint-disable camelcase */
import {z} from 'zod'

import {TASK_TYPE_VALUES} from '../task-types.js'

/**
 * Per-event schema for `task_created`.
 *
 * Funnel entry point. `has_files` / `has_folder` are booleans only — the
 * actual paths are forbidden, never enter the analytics payload.
 *
 * `task_id` is an internal UUID generated by the daemon; it is not user PII
 * and exists solely to correlate `task_created` with later
 * `task_completed` / `task_failed` events.
 */
export const TaskCreatedSchema = z
  .object({
    has_files: z.boolean(),
    has_folder: z.boolean(),
    /**
     * M17 follow-up: project-scoped join key, matching the convention every
     * other handler-emitted event uses (vc-*, review-*, source-*, worktree-*,
     * brv-init, context-tree-file-edited, webui-session-*). Optional because
     * TaskInfo.projectPath is `?: string` — when the router does not resolve
     * a project context the emit omits the field rather than fabricating one.
     */
    project_path_hash: z.string().regex(/^[0-9a-f]{64}$/).optional(),
    task_id: z.string().min(1),
    task_type: z.enum(TASK_TYPE_VALUES),
  })
  .strict()

export type TaskCreatedProps = z.infer<typeof TaskCreatedSchema>
